### ISSUE TITLE
Unable to run gist-* commands on emacs 25.0.50.1

### ISSUE THREAD

**Issue by kaushalmodi** [sigma/gh.el#44]
Hi,

This package runs great for me on emacs 24.4.

For the same init.el and freshly recompiled elpa directory, emacs 25.0.50.1 gives the below error when doing `M-x gist-list`.

From the content in the error, it looks like it fetched the gist list alright but am unable to understand why it errored out. The two files fetched from my gist list match up with [my gist](https://gist.github.com/kaushalmodi).

I tried edebug but I lost a way to debug further as the error is generated in the emacs source: `cl-generic.el`

If it is an emacs bug (it very likely can be as I built it from the latest today on emacs git), how do I describe it when filing emacs bug report?

<pre>
cl-no-applicable-method: No applicable method for %S: pcache-entry-valid-p, [object gh-cache-entry "gh-cache-entry" 1422398334.409232 nil ([object gh-gist-gist "gh-gist-gist" ([object gh-gist-gist-file "gh-gist-gist-file" "word_match_all_letters.el" 1050 "https://gist.githubusercontent.com/kaushalmodi/dcb9e54fae158211f226/raw/2b4230d42792171431aa5a9292b42d4e620604a1/word_match_all_letters.el" nil]) t "" "2015-01-26T16:42:11Z" "2015-01-26T16:46:57Z" "https://gist.github.com/dcb9e54fae158211f226.git" "https://gist.github.com/dcb9e54fae158211f226.git" ...] [object gh-gist-gist "gh-gist-gist" ([object gh-gist-gist-file "gh-gist-gist-file" "test-hydra.el" 2163 "https://gist.githubusercontent.com/kaushalmodi/b04368e07aa89a28545b/raw/20ebfe8274b4a3aeeedc2e6d7b33905d49d75f12/test-hydra.el" nil]) t "" "2015-01-20T18:13:19Z" "2015-01-20T18:21:19Z" "https://gist.github.com/b04368e07aa89a28545b.git" "https://gist.github.com/b04368e07aa89a28545b.git" ...]) nil nil]
</pre>

Many thanks!

**Comment by sigma** [comment]
Hi,

I'm not too sure at this point. Looks like the gh-cache-entry class is not considered a pcache-entry, although it most definitely inherits from it...
Note that eieio seems to be in a state of flux in current emacs master, so an upstream bug is possible, but that seems like an unlikely regression.
Actually I updated pcache.el very recently to deal with some emacs 25 breakage. Would you mind telling me which versions of pcache.el, gh.el and even gist.el you're using (just throw in the emacs git sha1, while we're at it :))
Thanks !

**Comment by kaushalmodi** [comment]
I am on emacs git version: c7effd7cacc5505933c32221bb25bea791b589e0

pcache.el: `pcache-20150125.1653/pcache.el`
gh.el: `gh-20150126.1125/gh.el`
gist.el: `gist-20141230.158/gist.el`

**Comment by sigma** [comment]
sorry, I'm unable to reproduce that issue, even when using all those exact versions. Just in case you might want to rm -rf ~/.emacs.d/var/pcache to start with a fresh cache, although I can't imagine how that would mess up the class hierarchy... :(

**Comment by kaushalmodi** [comment]
I have a feeling that this issue is similar to this issue I had on `sx` package. That issue got resolved when I deleted the `.emacs.d/url/` folder. But deleting the `var/` folder does not help me.

When I enable debug on error, the error is `(wrong-type-argument stringp `. In the log containing tens of thousands of characters, I also noticed messages like `[#[... "\306\307\310\311\"\310\312\"` and `url-request-data url-request-method ... high eieio-oref :method` . Note the ellipsis, 3 dots.. is that expected?

Here is the debug info after the `(wrong-type-argument stringp ` error:
I see the ellipsis in the the `gists_url` and `html_url` alist members. Is that expected?

<pre>
(((owner (site_admin . :json-false)
         (type . "User")
         (received_events_url . "https://api.github.com/users/kaushalmodi/received_events")
         (events_url . "https://api.github.com/users/kaushalmodi/events{/privacy}")
         (repos_url . "https://api.github.com/users/kaushalmodi/repos")
         (organizations_url . "https://api.github.com/users/kaushalmodi/orgs")
         (subscriptions_url . "https://api.github.com/users/kaushalmodi/subscriptions")
         (starred_url . "https://api.github.com/users/kaushalmodi/starred{/owner}{/repo}")
         (gists_url . "https://api.github.com/users/kaushalmodi/gists{/gist_id}") ...)
  (comments_url . "https://api.github.com/gists/dcb9e54fae158211f226/comments")
  (user)
  (comments . 0)
  (description . "")
  (updated_at . "2015-01-26T16:46:57Z")
  (created_at . "2015-01-26T16:42:11Z")
  (public . t)
  (files (word_match_all_letters\.el (size . 1050)
                                     (raw_url . "https://gist.githubusercontent.com/kaushalmodi/dcb9e54fae158211f226/raw/2b4230d42792171431aa5a9292b42d4e620604a1/word_match_all_letters.el")
                                     (language . "Emacs Lisp")
                                     (type . "text/plain")
                                     (filename . "word_match_all_letters.el")))
  (html_url . "https://gist.github.com/dcb9e54fae158211f226") ...)
 
 ((owner (site_admin . :json-false)
         (type . "User")
         (received_events_url . "https://api.github.com/users/kaushalmodi/received_events")
         (events_url . "https://api.github.com/users/kaushalmodi/events{/privacy}")
         (repos_url . "https://api.github.com/users/kaushalmodi/repos")
         (organizations_url . "https://api.github.com/users/kaushalmodi/orgs")
         (subscriptions_url . "https://api.github.com/users/kaushalmodi/subscriptions")
         (starred_url . "https://api.github.com/users/kaushalmodi/starred{/owner}{/repo}")
         (gists_url . "https://api.github.com/users/kaushalmodi/gists{/gist_id}") ...)
  (comments_url . "https://api.github.com/gists/b04368e07aa89a28545b/comments")
  (user)
  (comments . 0)
  (description . "")
  (updated_at . "2015-01-20T18:21:19Z")
  (created_at . "2015-01-20T18:13:19Z")
  (public . t)
  (files (test-hydra\.el (size . 2163)
                         (raw_url . "https://gist.githubusercontent.com/kaushalmodi/b04368e07aa89a28545b/raw/20ebfe8274b4a3aeeedc2e6d7b33905d49d75f12/test-hydra.el")
                         (language . "Emacs Lisp")
                         (type . "text/plain")
                         (filename . "test-hydra.el")))
  (html_url . "https://gist.github.com/b04368e07aa89a28545b") ...))
</pre>

I don't know much about caches, but does this comment from @vermiculus from that sx issue discussion apply here:
> Is it possibly an issue with princ (or whatever we're using)? Perhaps the data structure is deeper than the printing defaults.

And [this](https://github.com/vermiculus/sx.el/commit/2c9e84e67a54c163fd194194dc2a4f0266336cc9) is the fix that followed.

**Comment by sigma** [comment]
ok, let me have a look again. I think the ellipsis is just the printer trying to keep things controlled, but I don't know that I am using the string representation of anything internally. So while it's expected to see those in the various logs, they shouldn't be part of anything that's actually used in the code.

Out of curiosity, would you mind giving the 'next' branch a try? I started rolling out a new deserialization code powered by marshal.el. For all I know it might help

**Comment by kaushalmodi** [comment]
Thanks. I tried that but now I am getting a different error:

A<pre>
Debugger entered--Lisp error: (wrong-type-argument symbolp [defclass gh-gist-gist ([defclass gh-ref-object ([defclass gh-object ([defclass marshal-base nil (gh-gist-gist-file gh-gist-gist gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-comment gh-user gh-ref-object gh-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ()) nil nil nil [] nil nil nil nil nil nil (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--marshal-base] (:custom-groups (default))]) (gh-repos-ref gh-repos-repo-stub gh-gist-gist-file gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-oauth-app gh-ref-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ()) nil nil nil [] nil nil nil nil nil nil (-marshal-info -type-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--gh-object] (:custom-groups (default) :marshal-default-spec gh-marshal-default-spec :method-invocation-order :c3)] [defclass marshal-base nil (gh-gist-gist-file gh-gist-gist gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-comment gh-user gh-ref-object gh-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ()) nil nil nil [] nil nil nil nil nil nil (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--marshal-base] (:custom-groups (default))]) (gh-issues-milestone gh-issues-label gh-issues-issue gh-pulls-request-stub gh-repos-repo gh-gist-gist gh-oauth-authorization gh-comment gh-user) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data (id (0) url (1) html-url (2))) (id url html-url) (unbound unbound unbound) (nil nil nil) [t string t] (nil nil nil) (nil nil nil) ((default) (default) (default)) (nil nil nil) (nil nil nil) ((:id . id) (:url . url) (:html-url . html-url)) (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--gh-ref-object unbound unbound unbound] (:custom-groups (default) :marshal-default-spec gh-marshal-default-spec :method-invocation-order :c3)] [defclass gh-gist-gist-stub ([defclass gh-object ([defclass marshal-base nil (gh-gist-gist-file gh-gist-gist gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-comment gh-user gh-ref-object gh-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ()) nil nil nil [] nil nil nil nil nil nil (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--marshal-base] (:custom-groups (default))]) (gh-repos-ref gh-repos-repo-stub gh-gist-gist-file gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-oauth-app gh-ref-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ()) nil nil nil [] nil nil nil nil nil nil (-marshal-info -type-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--gh-object] (:custom-groups (default) :marshal-default-spec gh-marshal-default-spec :method-invocation-order :c3)] [defclass marshal-base nil (gh-gist-gist-file gh-gist-gist gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-comment gh-user gh-ref-object gh-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ()) nil nil nil [] nil nil nil nil nil nil (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--marshal-base] (:custom-groups (default))]) (gh-gist-gist) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data (files (0) public (1) description (2))) (files public description) (nil unbound unbound) (nil nil nil) [list t t] (nil nil nil) (nil nil nil) ((default) (default) (default)) (nil nil nil) (nil nil nil) ((:files . files) (:public . public) (:description . description)) (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--gh-gist-gist-stub nil unbound unbound] (:custom-groups (default) :documentation "Class for user-created gist objects" :marshal-default-spec gh-marshal-default-spec :method-invocation-order :c3)] [defclass marshal-base nil (gh-gist-gist-file gh-gist-gist gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-comment gh-user gh-ref-object gh-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ()) nil nil nil [] nil nil nil nil nil nil (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--marshal-base] (:custom-groups (default))]) nil #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data (id (0) url (1) html-url (2) files (3) public (4) description (5) date (6) update (7) push-url (8) pull-url (9) comments (10) user (11) history (12) forks (13))) (id url html-url files public description date update push-url pull-url comments user history forks) (unbound unbound unbound nil unbound unbound unbound unbound unbound unbound unbound nil nil nil) (nil nil nil nil nil nil nil nil nil nil nil nil nil nil) [t string t list t t t t t t t t list t] (nil nil nil nil nil nil nil nil nil nil nil nil nil nil) (nil nil nil nil nil nil nil nil nil nil nil nil nil nil) ((default) (default) (default) (default) (default) (default) (default) (default) (default) (default) (default) (default) (default) (default)) (nil nil nil nil nil nil nil nil nil nil nil nil nil nil) (nil nil nil nil nil nil nil nil nil nil nil nil nil nil) ((:id . id) (:url . url) (:html-url . html-url) (:files . files) (:public . public) (:description . description) (:date . date) (:update . update) (:push-url . push-url) (:pull-url . pull-url) (:comments . comments) (:user . user) (:history . history) (:forks . forks)) (-marshal-info -type-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--gh-gist-gist unbound unbound unbound nil unbound unbound unbound unbound unbound unbound unbound nil nil nil] (:custom-groups (default) :documentation "Gist object" :marshal-default-spec gh-marshal-default-spec :method-invocation-order :c3)])
  eieio--class-precedence-c3([defclass gh-gist-gist ([defclass gh-ref-object ([defclass gh-object ([defclass marshal-base nil (gh-gist-gist-file gh-gist-gist gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-comment gh-user gh-ref-object gh-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil nil nil [] nil nil nil nil nil nil (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) (... ...) nil (protected protected) [nil nil] [eieio-class-tag--marshal-base] (:custom-groups ...)]) (gh-repos-ref gh-repos-repo-stub gh-gist-gist-file gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-oauth-app gh-ref-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil nil nil [] nil nil nil nil nil nil (-marshal-info -type-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--gh-object] (:custom-groups (default) :marshal-default-spec gh-marshal-default-spec :method-invocation-order :c3)] [defclass marshal-base nil (gh-gist-gist-file gh-gist-gist gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-comment gh-user gh-ref-object gh-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil nil nil [] nil nil nil nil nil nil (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--marshal-base] (:custom-groups (default))]) (gh-issues-milestone gh-issues-label gh-issues-issue gh-pulls-request-stub gh-repos-repo gh-gist-gist gh-oauth-authorization gh-comment gh-user) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data (id (0) url (1) html-url (2) ...)) (id url html-url) (unbound unbound unbound) (nil nil nil) [t string t] (nil nil nil) (nil nil nil) ((default) (default) (default)) (nil nil nil) (nil nil nil) ((:id . id) (:url . url) (:html-url . html-url)) (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--gh-ref-object unbound unbound unbound] (:custom-groups (default) :marshal-default-spec gh-marshal-default-spec :method-invocation-order :c3)] [defclass gh-gist-gist-stub ([defclass gh-object ([defclass marshal-base nil (gh-gist-gist-file gh-gist-gist gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-comment gh-user gh-ref-object gh-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil nil nil [] nil nil nil nil nil nil (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) (... ...) nil (protected protected) [nil nil] [eieio-class-tag--marshal-base] (:custom-groups ...)]) (gh-repos-ref gh-repos-repo-stub gh-gist-gist-file gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-oauth-app gh-ref-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil nil nil [] nil nil nil nil nil nil (-marshal-info -type-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--gh-object] (:custom-groups (default) :marshal-default-spec gh-marshal-default-spec :method-invocation-order :c3)] [defclass marshal-base nil (gh-gist-gist-file gh-gist-gist gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-comment gh-user gh-ref-object gh-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil nil nil [] nil nil nil nil nil nil (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--marshal-base] (:custom-groups (default))]) (gh-gist-gist) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data (files (0) public (1) description (2) ...)) (files public description) (nil unbound unbound) (nil nil nil) [list t t] (nil nil nil) (nil nil nil) ((default) (default) (default)) (nil nil nil) (nil nil nil) ((:files . files) (:public . public) (:description . description)) (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--gh-gist-gist-stub nil unbound unbound] (:custom-groups (default) :documentation "Class for user-created gist objects" :marshal-default-spec gh-marshal-default-spec :method-invocation-order :c3)] [defclass marshal-base nil (gh-gist-gist-file gh-gist-gist gh-gist-history-entry gh-gist-history-change gh-gist-gist-stub gh-comment gh-user gh-ref-object gh-object) #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data ( ...)) nil nil nil [] nil nil nil nil nil nil (-type-info -marshal-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--marshal-base] (:custom-groups (default))]) nil #s(hash-table size 65 test eq rehash-size 1.5 rehash-threshold 0.8 data (id (0) url (1) html-url (2) files (3) public (4) description (5) date (6) update (7) push-url (8) pull-url (9) comments (10) user (11) history (12) forks (13) ...)) (id url html-url files public description date update push-url pull-url comments user history forks) (unbound unbound unbound nil unbound unbound unbound unbound unbound unbound unbound nil nil nil) (nil nil nil nil nil nil nil nil nil nil nil nil nil nil) [t string t list t t t t t t t t list t] (nil nil nil nil nil nil nil nil nil nil nil nil nil nil) (nil nil nil nil nil nil nil nil nil nil nil nil nil nil) ((default) (default) (default) (default) (default) (default) (default) (default) (default) (default) (default) (default) (default) (default)) (nil nil nil nil nil nil nil nil nil nil nil nil nil nil) (nil nil nil nil nil nil nil nil nil nil nil nil nil nil) ((:id . id) (:url . url) (:html-url . html-url) (:files . files) (:public . public) (:description . description) (:date . date) (:update . update) (:push-url . push-url) (:pull-url . pull-url) (:comments . comments) (:user . user) (:history . history) (:forks . forks)) (-marshal-info -type-info) (nil nil) [t t] (nil nil) (nil nil) ((default) (default)) nil (protected protected) [nil nil] [eieio-class-tag--gh-gist-gist unbound unbound unbound nil unbound unbound unbound unbound unbound unbound unbound nil nil nil] (:custom-groups (default) :documentation "Gist object" :marshal-default-spec gh-marshal-default-spec :method-invocation-order :c3)])
</pre>

**Comment by kaushalmodi** [comment]
This issue is resolved as of [this commit:8e010c...](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=8e010cf6e7486fae28ec6de80f098c793aee28f3) from emacs git.

I am still curious why you were unable to replicate this issue.

**Comment by sigma** [comment]
hmm, very weird instead. I guess it's possible that I failed to cleanup some .elc in my emacs repo, although I tried clean everything carefully
