### ISSUE TITLE
Add semver tags for MELPA stable.

### ISSUE THREAD

**Issue by mkleehammer** [sigma/gh.el#46]
I am unable to install magit-gh-pull from MELPA stable because it has gh as a dependency.

Unlike MELPA, MELPA stable doesn't make a package until it seems tag with major.minor.patch format.  I am actually expecting stable to be the primary repository over time.

Thanks.

**Comment by mkleehammer** [comment]
Now that I look at the tags, I believe it is the leading "v" on them that is keeping MELPA stable from picking them up.

**Comment by sigma** [comment]
Hi, feel free to open a bug on the melpa side for this. Official releases of gh.el are published on marmalade.

**Comment by rnkn** [comment]
The release tags are correct, it is apparently an issue with `.gitmodules` using ssh, as MELPA wants http. See https://github.com/milkypostman/melpa/issues/2834

Is it possible to switch the submodule over to http to get gh.el on stable?

**Comment by sigma** [comment]
done, thanks.
I'll go suggest a melpa improvement on the issue you linked
