### ISSUE TITLE
emacs 25 eieio inconsistencies

### ISSUE THREAD

**Issue by fakedrake** [sigma/gh.el#54]
This is for all api creation. Here is an example: `M-: (gh-gist-api)`

```
Debugger entered--Lisp error: (wrong-number-of-arguments (2 . 2) 1)
  #[514 "9\205P\301!\205PJ\211\262\205P\302!\205PG\303Y\205P\304H>\205P\305!\306\211\203K\211@\211\307H\262\211B\262\310DB\262A\266\202\202-\210\211\237\266\202\207" [cl-struct-eieio--class-tags boundp vectorp 12 0 eieio--class-precedence-list nil 1 eieio--static] 8 "\n\n(fn TAG TARGETS)"](nil)
  make-instance(gh-gist-api)
  apply(make-instance gh-gist-api nil)
  gh-gist-api()
  eval((gh-gist-api) nil)
```

And my emacs version

```
(version)
"GNU Emacs 25.0.50.1 (x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F27))\n of 2015-11-02"
```

**Comment by sigma** [comment]
I can't reproduce that on latest emacs 25 pretest, but eieio has changed quite a bit, and it kinda looks like a bytecode-level inconsistency. I suspect this comes from stale .elc generated by an older Emacs lying around.

Also, I'm fixing some other Emacs 25-related issues in the "next" branch, which should yield the next release. Please check that one out.

Tentatively closing that one
