### ISSUE TITLE
merging next into master

### ISSUE THREAD

**Issue by sigma** [sigma/gh.el#74]
I'm considering merging the "next" branch into "master". (one of the reasons being that it's where I'm kinda fixing the eieio-related disaster that Emacs 25 is introducing...)

A lot of work has gone into this branch, and some pretty intrusive changes took place (especially the introduction of a new response parsing structure based on https://github.com/sigma/marshal.el)

@aki2o @dgtized @IvanMalison @syohex @alexander-yakushev @nicferrier @lujun9972 you maintain packages that might be impacted by this merge. Would you mind checking if your package keeps working, and open issues/PR if things don't work as expected?

Thanks !

**Comment by IvanMalison** [comment]
Is there anything you might expect to break in particular?

**Comment by sigma** [comment]
@IvanMalison no, in theory that should be a drop-in replacement as the interface is preserved. But given the size of the change, I'm a little worried about what might fall through the cracks

**Comment by syohex** [comment]
My package `helm-open-github` works well with `next` branch of gh.el.

**Comment by syl20bnr** [comment]
This merge broke it for me. After the update `# r` asked my for my credentials and I end up with `JSON readtable error` or `byte-code: Wrong type argument: listp, "https://developer.github.com/v3"`.

Reverting back to version `gh-20160619.1751` fixed if for me.

**Comment by sigma** [comment]
yeah, it would seem that my changes to support emacs 25 are breaking emacs 24... *sigh*
I guess I'll need to work a bit more on that. thanks for trying it out !

**Comment by peterhadlaw** [comment]
How could one go about reverting to an older version? Excuse my lack of understanding. Right now I'm using Cask and Melpa to install 'magit-gh-pulls' (which depends on this). Thank you in advance!
