### ISSUE TITLE
Obsolete name passed to constructor

### ISSUE THREAD

**Issue by vermiculus** [sigma/gh.el#91]
Relevant emacs email thread: https://lists.gnu.org/archive/html/bug-gnu-emacs/2015-01/msg00530.html

When evaluating, say `(gh-issues-issue-list (gh-issues-api "API") user repo)` using `M-x eval-buffer`, the following warning appears:

```
Obsolete name arg "API" to constructor gh-issues-api
```

**Comment by Macroz** [comment]
You don't have to give the argument at all so you can just `(gh-issues-api)`.

**Comment by vermiculus** [comment]
I trust this is accurate, though I've not tried it.  Thanks for following-up :smile:
