### ISSUE TITLE
gh autoloads actually load quite a bit of code

### ISSUE THREAD

**Issue by IvanMalison** [sigma/gh.el#95]
While using benchmark-init to reduce my emacs initialization time, I noticed that gh-autoloads loads many more modules than an autoload ever should

```
  │ ├─[~/.emacs.d/straight/build/gh/gh-autoloads.el load 26ms]
  │ │ ├─[gh-profile require 3ms]
  │ │ │ ├─[url-parse require 3ms]
  │ │ │ │ ├─[auth-source require 5ms]
  │ │ │ │ │ ├─[mm-util require 24ms]
  │ │ │ │ │ │ ├─[help-fns require 2ms]
  │ │ │ │ │ │ ╰─[mail-prsvr require 1ms]
  │ │ │ │ │ ╰─[password-cache require 1ms]
  │ │ │ │ ╰─[url-vars require 1ms]
  │ │ │ ╰─[rx require 1ms]
  │ │ ├─[marshal require 5ms]
  │ │ │ ├─[ht require 0ms]
  │ │ │ ╰─[json require 2ms]
  │ │ │   ╰─[map require 1ms]
  │ │ ╰─[eieio require 18ms]
  │ │   ╰─[eieio-core require 2ms]
```

The reason for this is that gh-defclass instances are often marked as autoloads which requires that the autoload file load gh-common, which then loads

```
(require 'dash)
(require 'marshal)
(require 's)
(require 'gh-profile)
```
etc. etc.

**Comment by xuchunyang** [comment]
I encounter the same problem, after I install a package (helm-open-github) which depends on gh, my emacs startup time increase about 2 seconds.

It looks like gh.el is a library, maybe it doesn't need autoload at all, since packages use it will require it anyway (?)

**Comment by sigma** [comment]
thanks for reporting this. To be honest my interest in startup time is opportunistic at best :)
That said, I would absolutely welcome patches to improve that situation !

from a quick glance, cutting the loading of gh-profile should be quite trivial, but I'm not sure how much it contributes to the overall load time. Also Ivan's numbers don't seem to add up to 2 seconds?
Any chance either of you could provide a complete breakdown?

**Comment by xuchunyang** [comment]
> Also Ivan's numbers don't seem to add up to 2 seconds?
> Any chance either of you could provide a complete breakdown?

Oh, that's probably because my laptop is old and not fast. Without gh.el installed, Emacs takes 6 seconds to start, with gh.el installed, Emacs takes 8 seconds.

**Comment by xuchunyang** [comment]
I encounter an error while trying `fix/load-time`

> Symbol’s function definition is void: s-replace

However this issue no longer bothers me any more because I decide to disable autoloads for gh.el with straight.el (an alternative to package.el). Without gh-autoloads.el, I can still successfully use helm-open-github (a package depends on gh.el).

**Comment by ylluminarious** [comment]
@sigma I am definitely seeing `gh` hurt my startup time as well. In fact, this became an issue of discussion recently on `emacs-devel`. Stefan Monnier is currently trying to implement a patch which allows for a pre-computed concatenation of autoload files from ELPA packages in order to speed up startup time for Emacs users. I had some issues with `marshal` being used in `gh`'s autoload file, which can be seen [here.](https://lists.gnu.org/archive/html/emacs-devel/2018-02/msg00031.html)

I also saw this from [`benchmark-init`](https://github.com/dholm/benchmark-init-el):

```
  │ ├─[~/.emacs.d/elpa/gh-20180112.1110/gh-autoloads load 17ms]
  │ │ ├─[gh-profile require 1ms]
  │ │ │ ├─[url-parse require 6ms]
  │ │ │ │ ├─[auth-source require 9ms]
  │ │ │ │ │ ├─[gnus-util require 10ms]
  │ │ │ │ │ ├─[mm-util require 19ms]
  │ │ │ │ │ │ ├─[help-fns require 7ms]
  │ │ │ │ │ │ ╰─[mail-prsvr require 5ms]
  │ │ │ │ │ ╰─[password-cache require 4ms]
  │ │ │ │ ╰─[url-vars require 5ms]
  │ │ │ ╰─[rx require 6ms]
  │ │ ├─[s require 5ms]
  │ │ ├─[marshal require 17ms]
  │ │ ├─[dash require 9ms]
  │ │ ╰─[eieio require 10ms]
  │ │   ╰─[eieio-core require 8ms]
```

As you can see, `gh` is really loading a lot of stuff there and it really stands out in the midst of so many other autoload files which are down to 0ms or at least less than 10ms.

**Comment by sigma** [comment]
@ylluminarious so can you try #99 and let me know if that makes a difference at all? If I'm not mistaken, I expect only `eieio` and `eieio-core` to remain in that tree (not much I can do about that at this point without potentially changing downstream consumers of `gh.el`)

Other than that, I guess I don't know how to read those numbers. Even in the worst case when I add everything, the total is still pretty low...

**Comment by sigma** [comment]
oh and also `marshal` itself should load faster since sigma/marshal.el#11

**Comment by ylluminarious** [comment]
@sigma Ok, thank you. I will try to give feedback on those changes when I get a chance.

**Comment by ylluminarious** [comment]
@sigma Ok, I've tried out your patches but I don't really have any good news to report. I pulled in your changes via:

```sh
$ wget https://patch-diff.githubusercontent.com/raw/sigma/gh.el/pull/99.diff
```

Then I applied the diff:

```sh
$ patch -p1 < 99.diff
```

I ran Emacs again, but it seems that `gh.el` is actually *slower* now:

```
  │ ├─[~/.emacs.d/elpa/gh-20180112.1110/gh-autoloads load 131ms]
  │ │ ├─[gh-profile require 1ms]
  │ │ │ ├─[url-parse require 6ms]
  │ │ │ │ ├─[auth-source require 9ms]
  │ │ │ │ │ ├─[gnus-util require 11ms]
  │ │ │ │ │ ├─[mm-util require 19ms]
  │ │ │ │ │ │ ├─[help-fns require 8ms]
  │ │ │ │ │ │ ╰─[mail-prsvr require 5ms]
  │ │ │ │ │ ╰─[password-cache require 4ms]
  │ │ │ │ ╰─[url-vars require 5ms]
  │ │ │ ╰─[rx require 7ms]
  │ │ ├─[s require 5ms]
  │ │ ├─[marshal require 18ms]
  │ │ ├─[dash require 9ms]
  │ │ ╰─[eieio require 12ms]
  │ │   ╰─[eieio-core require 9ms]
```

I have no idea how that could be, but I have a *very* peculiar setup right now so it could very well be my fault. In any case, I was hoping for `gh.el`'s time to drop down to 1ms or 0ms, which most of my other packages' autloads are. I'm currently trying to get my startup time below 1 second, so I don't really want packages with such hefty autoloads. Moreover, I only had one package that depends on `gh.el` and I haven't used it for a while so I went ahead and uninstalled it along with `gh.el`. But thank you for the efforts! I hope you can improve your autoloads' time by even more!

**Comment by sigma** [comment]
@ylluminarious well, just applying the diff will not cut it, you also need to regenerate the `gh-autoloads.el` file. For example by running `M-x update-directory-autoloads`

**Comment by ylluminarious** [comment]
@sigma Sorry for the delayed response. I did that as well.

**Comment by raxod502** [comment]
@sigma Sorry if I'm missing something here—but is `gh.el` intended to be used directly by users? It doesn't seem like it to me, since no interactive functions are exposed.

If `gh.el` is purely a library, then **why does it have _any_ autoloads?**

**Comment by sigma** [comment]
apparently autoloads broke in Emacs 28 anyway, so #107 removed them.
Hopefully that fixes this
